version: "3.2"

services:
  dev:
    container_name: node-template
    build:
      context: ./
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "/usr/local/bin/node-template --dev --ws-external"
