name: 'Build Docker image'
on:
  push:
    branches:
      - 'feat/docker-build' #TODO for testing in this branch
env:
  ECR_REPOSITORY: 'crb-substrate-node'
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
jobs:
  build-and-push:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v1'
      - name: 'Configure AWS credentials'
        uses: 'aws-actions/configure-aws-credentials@v1'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
      - name: 'Login to Amazon ECR'
        id: 'login-ecr'
        uses: 'aws-actions/amazon-ecr-login@v1'
      - name: 'Build and push image'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY
